# Generated by Django 4.0.6 on 2022-07-31 13:48

from django.db import migrations, models
# import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_published', models.DateTimeField(verbose_name='date published')),
                ('article_content', models.TextField()),
                ('article_title', models.CharField(max_length=200)),
                ('article_image', models.ImageField(upload_to='images/')),
                ('article_slug', models.SlugField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
