# Generated by Django 4.0.6 on 2022-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comfort_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='durability_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='performance_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
